server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://database:5432/postgres
    #url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      #ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    #show-sql: true
  mail:
    #host: localhost
    host: mailSender
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 180000 # 86400000 a day
      refresh-token:
        expiration: 604800000 # 7 days
